FROM node:16

WORKDIR /home/node/app

COPY slacker/package.json ./

ENV SLACK_BOT_TOKEN ${SLACK_BOT_TOKEN}
ENV SLACK_SIGNING_SECRET ${SLACK_SIGNING_SECRET}
ENV CHANNEL_ID ${CHANNEL_ID}
ENV DB_USER ${DB_USER}
ENV DB_PASSWORD ${DB_PASSWORD}

RUN npm install

RUN npm install mysql

COPY slacker/ ./

# CMD ["node", "/home/node/app/app.js"]
